### ISSUE TITLE
how to install this one over ubuntu

### ISSUE THREAD

**Issue by wanghaisheng** [indraastra/nn-ocr#1]
thx very much

**Comment by wanghaisheng** [comment]
could you write a simple  readme

**Comment by indraastra** [comment]
Hey, thanks for the interest. Please take a look at the updated README and let me know if you're able to get up and running. This is all meant to be experimental work so there may still be some kinks I've overlooked.

**Comment by wanghaisheng** [comment]
@indraastra  Is "requirements.txt" missing

**Comment by indraastra** [comment]
Sorry about that, added now. Note that I'm using python 3 in the project so you may want to ensure you have an appropriate dev environment set up before installing requirements (I usually use virtualenvwrapper or conda).

**Comment by wanghaisheng** [comment]
your OS ?
i run  the following over macos 10.12  and ubuntu 14.04   
```
➜  nn-ocr git:(master) ✗ pip3 install -r requirements.txt
Collecting anaconda-client==1.4.0 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement anaconda-client==1.4.0 (from -r requirements.txt (line 1)) (from versions: 1.1.1, 1.2.2)
No matching distribution found for anaconda-client==1.4.0 (from -r requirements.txt (line 1))
```

**Comment by indraastra** [comment]
I'm using conda on OSX but as it seems you're not, you can delete that line and try again.

**Comment by wanghaisheng** [comment]
install conda  and run the following 
```
(py35) data-clear@dataclear:~/dev/ocr/nn-ocr$ python -m dataset.en preview_data --font_limit 100
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/data-clear/anaconda3/envs/py35/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/data-clear/anaconda3/envs/py35/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/data-clear/dev/ocr/nn-ocr/dataset/en.py", line 11, in <module>
    from dataset.dataset import save, preview
  File "/home/data-clear/dev/ocr/nn-ocr/dataset/dataset.py", line 3, in <module>
    import matplotlib.pyplot as plt
  File "/home/data-clear/anaconda3/envs/py35/lib/python3.5/site-packages/matplotlib/pyplot.py", line 36, in <module>
    from matplotlib.figure import Figure, figaspect
  File "/home/data-clear/anaconda3/envs/py35/lib/python3.5/site-packages/matplotlib/figure.py", line 35, in <module>
    from matplotlib import _image
ImportError: /home/data-clear/anaconda3/envs/py35/lib/python3.5/site-packages/matplotlib/_image.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZNSt14overflow_errorC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
`
``

**Comment by indraastra** [comment]
Hmm, it's possible pip and conda aren't playing nicely. Did you install matplotlib through conda or pip? (Try `pip uninstall matplotlib` and `conda install matplotlib` if you used pip.)

**Comment by indraastra** [comment]
p.s. you should be able to just run python and import matplotlib - no reason to try running the code until that works.
